version: "3.7"
services:
  db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h db -U admin -p 5432"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend-network

volumes:
    db-data:

networks:
    backend-network:
        driver: bridge
