version: "3.7"
services:
    product_competition:
        build:
            context: ./
            dockerfile: dockerfile
        networks:
            - backend-network
        depends_on:
            - db
        ports:
            - "8000:8000"

    db:
        image: postgres:16.0
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h db -U admin -p 5432"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend-network
    # mongo:
    #     image: mongo:latest  # 使用官方的MongoDB的Image
    #     restart: always
    #     environment:
    #         MONGO_INITDB_DATABASE: mongodb
    #         MONGO_INITDB_ROOT_USERNAME: admin
    #         MONGO_INITDB_ROOT_PASSWORD: admin
    #     ports:
    #         - "27017:27017"  # 將MongoDB端口映射到主機的端口
    #     networks:
    #         - backend-network  # 連接到自定義網路

volumes:
    db-data:

networks:
    backend-network:
        driver: bridge



